<?php


namespace App\Twig;


use Twig\Extension\AbstractExtension;
use Twig\Extension\GlobalsInterface;
use Twig\TwigFilter;

class AppExtension extends AbstractExtension implements GlobalsInterface
{

    /**
     * @var string
     */
    private $locale;

    public function __construct(string $locale)
    {
        $this->locale = $locale;
    }

    public function getFilters()
    {
        return [
            new TwigFilter('price', [$this, 'priceFilter'])
        ];
//        return parent::getFilters(); // TODO: Change the autogenerated stub
    }

    public function getGlobals(): array
    {
        return [
            'locale' => $this->locale,

        ];
        // TODO: Implement getGlobals() method.
    }

    public function priceFilter($number  )
    {
        return '$' . number_format($number, 2, '.',',');
    }
}